# Netlify configuration file

[build]
  # Command to build the project
  command = "next build"

  # Directory to publish
  publish = ".next"

# The following plugin is essential for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
